// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"github.com/offblocks/offblocks-common/types"
)

// Defines values for AccountIdentifierType.
const (
	Iban AccountIdentifierType = "iban"
)

// Account defines model for Account.
type Account struct {
	// CreatedAt ISO-8601 timestamp
	CreatedAt DateTime  `json:"createdAt"`
	Id        AccountId `json:"id"`

	// Identifier Account identifier
	Identifier string `json:"identifier"`

	// IdentifierType Type of the account identifier
	IdentifierType AccountIdentifierType `json:"identifierType"`

	// Name Account name
	Name string `json:"name"`

	// UpdatedAt ISO-8601 timestamp
	UpdatedAt DateTime `json:"updatedAt"`

	// WalletId Blockchain wallet identifier (0x for Ethereum)
	WalletId WalletId `json:"walletId"`
}

// AccountId defines model for AccountId.
type AccountId = UUID

// AccountIdentifierType Type of the account identifier
type AccountIdentifierType string

// DateTime ISO-8601 timestamp
type DateTime = types.Time

// Decimal Decimal number
type Decimal = types.Decimal

// Payment defines model for Payment.
type Payment struct {
	// Amount Decimal number
	Amount Decimal `json:"amount"`

	// CreatedAt ISO-8601 timestamp
	CreatedAt DateTime `json:"createdAt"`

	// Currency Payment currency (ISO-4217)
	Currency    string    `json:"currency"`
	Destination AccountId `json:"destination"`

	// DestinationName Destination account name
	DestinationName string `json:"destinationName"`

	// GatewayWalletId Blockchain wallet identifier (0x for Ethereum)
	GatewayWalletId WalletId  `json:"gatewayWalletId"`
	Id              PaymentId `json:"id"`

	// UpdatedAt ISO-8601 timestamp
	UpdatedAt DateTime `json:"updatedAt"`

	// UsdAmount Decimal number
	UsdAmount Decimal `json:"usdAmount"`
}

// PaymentId defines model for PaymentId.
type PaymentId = UUID

// UUID defines model for UUID.
type UUID = types.UUID

// WalletId Blockchain wallet identifier (0x for Ethereum)
type WalletId = string

// CreateAccountJSONBody defines parameters for CreateAccount.
type CreateAccountJSONBody struct {
	// Identifier Account identifier
	Identifier string `json:"identifier"`

	// IdentifierType Type of the account identifier
	IdentifierType AccountIdentifierType `json:"identifierType"`

	// Name Account name
	Name string `json:"name"`

	// WalletId Blockchain wallet identifier (0x for Ethereum)
	WalletId WalletId `json:"walletId"`
}

// InitiatePaymentJSONBody defines parameters for InitiatePayment.
type InitiatePaymentJSONBody struct {
	// Amount Decimal number
	Amount Decimal `json:"amount"`

	// Currency Payment currency (ISO-4217)
	Currency    string    `json:"currency"`
	Destination AccountId `json:"destination"`
}

// SubmitPaymentJSONBody defines parameters for SubmitPayment.
type SubmitPaymentJSONBody struct {
	// PayerWalletId Blockchain wallet identifier (0x for Ethereum)
	PayerWalletId WalletId `json:"payerWalletId"`

	// UsdAmount Decimal number
	UsdAmount Decimal `json:"usdAmount"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody CreateAccountJSONBody

// InitiatePaymentJSONRequestBody defines body for InitiatePayment for application/json ContentType.
type InitiatePaymentJSONRequestBody InitiatePaymentJSONBody

// SubmitPaymentJSONRequestBody defines body for SubmitPayment for application/json ContentType.
type SubmitPaymentJSONRequestBody SubmitPaymentJSONBody
